# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('boleta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('edad', models.IntegerField(blank=True)),
            ],
        ),
    ]
