# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
